---
title: "Converting Bibliography to Excel Document"
date: "`r Sys.Date()`"
format: html
bibliography: references.bib
csl: "your_citation_style.csl"
execute:
  echo: true
  warning: false
  message: false
---

```{r}

require(RefManageR)
require(dplyr)
require(stringr)
require(knitr)

```


```{r}

bib = "references.bib"
bib = ReadBib(bib, check = FALSE)
bib = as.data.frame(bib)

names(bib) = gsub("[^[:alnum:]_]", "_", names(bib))

extract = function(author_field) {
  if (is.na(author_field) || author_field == "") return(NA)
  authors = unlist(strsplit(author_field, " and "))
  first_author = authors[1]
  
  if (grepl(",", first_author)) {
    last_name = str_trim(unlist(strsplit(first_author, ","))[1])
  } else {
    name_parts = unlist(strsplit(first_author, " "))
    last_name = name_parts[length(name_parts)]
  }
  return(last_name)
}


bib$First_Author_Last_Name = sapply(bib$author, extract)
bib = bib %>% relocate(First_Author_Last_Name, .before = everything())

csv = "ResearchRabbit.csv"
write.csv(bib, file = csv, row.names = FALSE)
knitr::kable(head(bib))


```

